---
- name: 'Install, configure and start k3s'
  hosts: 'k3s1'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.install_k3s'
      tls_san:
        - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        - "k3s.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.sslip.io"
