---

- name: 'Runplaybook-bootstrap_python.yml'
  ansible.builtin.import_playbook: playbook-bootstrap_python.yml

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-postgresql_installation.yml'
  ansible.builtin.import_playbook: playbook-postgresql_installation.yml

- name: 'Run playbook-sharry_installation.yml'
  ansible.builtin.import_playbook: playbook-sharry_installation.yml
