---
- name: 'Delete the kubeconfig file on the Ansible control host'
  hosts: 'localhost'
  gather_facts: false
  become: false

  tasks:

    - name: 'Remove k3s-kubeconfig on Ansible control host'
      ansible.builtin.file:
        path: 'k3s-kubeconfig'
        state: 'absent'
